name: Python Package using Conda

on:
  push:
  schedule:
    - cron: "30 * * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas==1.5.3
          pip install requests==2.31.0
          pip install tweepy==4.14.0
        # Add error handling if any of the installations fail
        # Add comments explaining the reason behind specific versions

      - name: Run Python Script
        run: python ./most_trendy_1h.py
