on:
  push:
  
  schedule:
        # First job: runs every 2 hours
    - cron: "0 */2 * * *"
    
    # Second job: runs every 2 hours and 15 minutes
    - cron: "15 1-23/2 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install numpy==1.21.2
          pip install pandas==1.5.3
          pip install requests==2.31.0
          pip install tweepy==4.14.0
          pip install yfinance==0.2.37
        # Add error handling if any of the installations fail
        # Add comments explaining the reason behind specific versions

      - name: Run Python Script
        run: python ./coinmarket_api_24h.py
